### ISSUE TITLE
adjust min-max to exclude outliers

### ISSUE THREAD

**Issue by burritojustice** [burritojustice/xyz_space_invader#13]
Certain data sets with extreme outliers do not lend themselves well to a color ramp, where one value far outside the range of most values "swamp" the color palette. (A good example of this is the AirBnB pricing data where the vast majority of prices are around $100-200 a night, but there are one or two at $10,000 a night.

![image](https://user-images.githubusercontent.com/3979711/57890169-be958280-77eb-11e9-88bf-d62313d8396c.png)

https://min-max--xyz-space-invader.netlify.com/?space=40ILezn0&token=AOsE9k2EdCdT8lEX12PDZ38&basemap=refill&buildings=0&points=0&lines=1&outlines=0&highlight=0&roads=1&water=0&colors=range&tags=entire_home%2Fapt%2Blistings&property=price&palette=viridisMagma&paletteFlip=false#13.68402401032391/34.1062/-118.4218

It would be helpful to have a way to lower max or raise min depending on the distribution of the data and these outliers.

Maybe there is a way to use the mean and median to detect that the distribution is not normal?

Perhaps an option to set max at three a standard deviations' above the mean, and color the outliers the 'highest' color?

**Comment by bcamper** [comment]
I've added a range filtering UI in the `sigma-filter` branch:

https://sigma-filter--xyz-space-invader.netlify.com/?space=40ILezn0&token=AOsE9k2EdCdT8lEX12PDZ38&basemap=refill&buildings=0&points=0&lines=1&outlines=0&highlight=0&roads=1&water=0&colors=range&tags=entire_home%2Fapt%2Blistings&property=price&palette=viridisMagma&paletteFlip=false#12.499999999999988/34.0969/-118.4127
https://github.com/burritojustice/xyz_space_invader/compare/sigma-filter

- Provides options to limit the value range by:
  - All values
  - Sigma 1, 2, 3, 4
  - Custom range
- Min/max inputs are provided, they auto-update as a preset is selected, and switch to "custom" filter mode when the value is edited by the user
- All values are still shown in the color swatches below, and the palette simply "stops" at either end of the min/max range and "holds" that color for further values (but still useful I think to see the underlying values).
- Right now this only applies to `range` filtering, but it could also apply to `rank`? In this case, the values beyond the min/max would be "squashed" into one bucket for rank count (this might actually require either coalescing the values in the palette swatch list, contra the above bullet point, or an additional implementation layer to handle this "rank collapsing").
- Note these parameters are *not* yet reflected in the query string, they will be but that work is TBD.

I'm not entirely happy with how complex the implementation in that branch turned out (may take another crack at it), but it seems to be working pretty well.

**Comment by bcamper** [comment]
Note, moved this branch to:

https://github.com/burritojustice/xyz_space_invader/tree/sigma-filter-rebase

https://sigma-filter-rebase--xyz-space-invader.netlify.com/?space=40ILezn0&token=AOsE9k2EdCdT8lEX12PDZ38&basemap=refill&buildings=0&points=0&lines=1&outlines=0&highlight=0&roads=1&water=0&colors=range&tags=entire_home%2Fapt%2Blistings&property=price&palette=viridisMagma&paletteFlip=false#12.499999999999988/34.0969/-118.4127

**Comment by bcamper** [comment]
Added to query string params: https://github.com/burritojustice/xyz_space_invader/commit/3799216d435ac7efc75e07558e45b84f5bdcbdf6
